version: "3.8"

services:
  server:
    container_name: server
    build: .
    env_file:
      - .env
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      - database
    networks:
      default:
        ipv4_address: 10.69.69.1

  database:
    container_name: database
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: road_damage
      MYSQL_USER: server
      MYSQL_PASSWORD: server
    networks:
      default:
        ipv4_address: 10.69.69.2

networks:
    default:
      ipam:
        config:
          - subnet: 10.69.69.0/24
