services:
  backend:
    build: .
    environment:
      - DATABASE_URL=./db.sqlite
    ports:
      - "8080:8080"
    restart: unless-stopped
    volumes:
      - ./timetables.db:/app/timetables.db
      - ./backend.log:/app/backend.log
